name: FinAgent CI

on:
  push:
    branches:
      - main

jobs:
  build-backend:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Build backend Docker image
        env:
          GROQ_API_KEY: ${{ secrets.GROQ_API_KEY }}
          FINNHUB_API_KEY: ${{ secrets.FINNHUB_API_KEY }}
        run: docker build -t finagent-backend ./backend

  build-frontend:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Build frontend Docker image
        run: docker build -t finagent-frontend ./frontend




        